### ISSUE TITLE
https -el lerheto, elovalasztok.hu domainnel elerheto szerverre telepites

### ISSUE THREAD

**Issue by utopszkij** [utopszkij/elovalasztok2018#4]

**Comment by magwas** [comment]
http://elovalasztok.edemokraciagep.org/

**Comment by magwas** [comment]
https://elovalasztok.edemokraciagep.org/
Beszéljük meg, hogy milyen certet akarunk a teszt szerverhez. Jó-e a mostani self-signed, adjak ki valamelyik saját CA-ból, vagy vegyünk pénzért olyat, amire konfig nélkül sem sír a böngésző?

**Comment by Gerviba** [comment]
Lehet, hogy megfelelő lenne egy [Let's Encrypt](https://letsencrypt.org/)-es cert is. Ingyenes és nem sír érte a böngésző. Azt nem tudom, hogy a többi megoldás mennyire időigényes, de ez olyan 3 parancs.

**Comment by utopszkij** [comment]
Nekem ez mindegy, nekem jó igy ahogy van.



2016. 11. 30. 22:42 keltezéssel, Árpád Magosányi írta:

**Comment by magwas** [comment]
tettem fel letsencrypt-es certet
